spring:
  datasource:
    url: jdbc:h2:mem:dev;DB_CLOSE_DELAY=-1
    username: devuser
    password: devpass
    driver-class-name: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate.hibernate.format_sql: true
  sql:
    init:
      mode: always